Get Started with Python for Data Science

Libraries or Modules

In [50]:
import math
import numpy
from scipy import stats

In [51]:
import math as mt
from numpy import random

In [52]:
import numpy as np

In [53]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [54]:
print(dataOne)

[[0.47680074 0.54609793 0.12920734 0.0072514  0.37549092]
 [0.10579224 0.22119003 0.25906862 0.57616832 0.1752089 ]
 [0.41204422 0.58989806 0.21977552 0.25547245 0.15714071]
 [0.15138873 0.11568342 0.14263302 0.39611521 0.79472788]
 [0.22065667 0.31742028 0.23559078 0.9051882  0.45633753]]


In [55]:
np.mean(dataOne)

0.3296939645990718

3 Functions test (math and stats)

In [56]:
mt.fsum(dataOne)

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
mt.trunc(dataOne)



In [ ]:
mt.cosh(dataOne[1,1])

In [ ]:
math.hypot(dataOne)

In [ ]:
stats.describe(dataOne)

In [ ]:
stats.tmean(dataOne)

In [ ]:
stats.kstat(dataOne)

Functions

In [ ]:
print('I Love data Science')

In [ ]:
variableName = 25
variableName1 = 'I Love data Science'
print(variableName1)

In [57]:
variableName = 25
type(variableName)

int

In [58]:
variableName = 25.0
type(variableName)

float

In [59]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [60]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [61]:
varOne = 25
varTwo = 'Hello'
varThree = str(varOne) + varTwo
print(varThree)

25Hello


Lists and Dictionaries

In [63]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [64]:
tel = {'jack': 4098, 'sape': 4139}

In [65]:
tel['jack']

4098

1.Try own your own

In [70]:
f1 = {'ferrari':238, 'McLaren':182, 'Williams':114, 'mercedes':102, 'teamlotus':79}

In [100]:
print(np.sum(f1['ferrari']+f1['McLaren']+f1['Williams']+f1['mercedes']+f1['teamlotus']))

715


In [99]:
top3 = (f1['ferrari'],f1['McLaren'],f1['Williams'])
print(mt.fsum(top3))

534.0


In [103]:
print(mt.fabs(top3[0]))

238.0


In [104]:
print(mt.gcd(top3[0],top3[1]))


14


Whirlwind Tour of Python

Chatper 3

In [105]:
# set the midpoint
midpoint = 5

# make two empty lists
lower = []; upper = []

# split the numbers into lower and upper
for i in range(10):
    if (i < midpoint):
        lower.append(i)
    else:
        upper.append(i)
        
print("lower:", lower)
print("upper:", upper)

lower: [0, 1, 2, 3, 4]
upper: [5, 6, 7, 8, 9]
